"""
Helper Functions Module
This module contains utility functions for text processing and formatting.
"""


def count_words(text: str) -> int:
    """
    Count the number of words in the text.
    
    Args:
        text: The text to count words in
    
    Returns:
        Number of words
    """
    if not text:
        return 0
    return len(text.split())


def count_characters(text: str, include_spaces: bool = True) -> int:
    """
    Count the number of characters in the text.
    
    Args:
        text: The text to count characters in
        include_spaces: Whether to include spaces in the count (default: True)
    
    Returns:
        Number of characters
    """
    if not text:
        return 0
    
    if include_spaces:
        return len(text)
    else:
        return len(text.replace(" ", ""))


def clean_text(text: str) -> str:
    """
    Clean and normalize text (remove extra whitespace and newlines).
    
    Args:
        text: The text to clean
    
    Returns:
        Cleaned text
    """
    if not text:
        return ""
    
    # Replace multiple newlines with single newline
    text = '\n'.join(line.rstrip() for line in text.split('\n'))
    
    # Replace multiple spaces with single space
    text = ' '.join(text.split())
    
    return text


def truncate_text(text: str, max_words: int = 1000) -> str:
    """
    Truncate text to a maximum number of words.
    
    Args:
        text: The text to truncate
        max_words: Maximum number of words to keep
    
    Returns:
        Truncated text
    """
    if not text:
        return ""
    
    words = text.split()
    
    if len(words) <= max_words:
        return text
    
    return ' '.join(words[:max_words]) + "..."


def estimate_read_time(text: str, words_per_minute: int = 200) -> str:
    """
    Estimate the time to read the text.
    
    Args:
        text: The text to estimate reading time for
        words_per_minute: Average reading speed (default: 200 wpm)
    
    Returns:
        Estimated read time as a string (e.g., "2 min", "1 min")
    """
    words = count_words(text)
    
    if words == 0:
        return "0 min"
    
    minutes = max(1, round(words / words_per_minute))
    return f"{minutes} min" if minutes > 1 else "1 min"


def format_for_download(title: str, content: str, metadata: dict = None) -> str:
    """
    Format text content for download as a .txt file.
    
    Args:
        title: Title of the document
        content: The main content
        metadata: Optional dictionary with metadata (e.g., {'Word Count': 100})
    
    Returns:
        Formatted text ready for download
    """
    lines = []
    
    # Add title
    lines.append("=" * 60)
    lines.append(title)
    lines.append("=" * 60)
    lines.append("")
    
    # Add metadata if provided
    if metadata:
        lines.append("METADATA:")
        lines.append("-" * 60)
        for key, value in metadata.items():
            lines.append(f"{key}: {value}")
        lines.append("")
        lines.append("-" * 60)
        lines.append("")
    
    # Add content
    lines.append(content)
    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by AI Content Summarizer")
    lines.append("=" * 60)
    
    return '\n'.join(lines)


def get_summary_type_description(summary_type: str) -> str:
    """
    Get a description for different summary types.
    
    Args:
        summary_type: Type of summary
    
    Returns:
        Description of the summary type
    """
    descriptions = {
        "short": "Concise 2-3 sentence overview",
        "detailed": "Comprehensive multi-paragraph summary",
        "bullet": "Key points in bullet format (5-8 points)",
    }
    return descriptions.get(summary_type, "Summary")


def get_tone_description(tone: str) -> str:
    """
    Get a description for different tones.
    
    Args:
        tone: The tone type
    
    Returns:
        Description of the tone
    """
    descriptions = {
        "professional": "Formal business tone",
        "simple": "Easy-to-understand language",
        "academic": "Scholarly and technical tone",
        "casual": "Friendly and conversational tone",
    }
    return descriptions.get(tone, "Tone")
